services:
  db:
    build:
      context: ./db
    container_name: pgjwt-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-server:
    build: 
      context: .
      dockerfile: auth-server/Dockerfile
    container_name: auth-server
    ports:
      - '4000:4000'
    env_file:
      - ./auth-server/.env
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    depends_on:
      - auth-server